FOGL-5397: error handling improved
dianomic/foglamp-north-influxdb pull request #12
Opened 2021-05-11 13:50 UTC by sstefano69

Signed-off-by: Stefano <stefano@dianomic.com>

2021-05-11 16:29 UTC, MarkRiddoch requested changes

2021-05-12 08:59 UTC, sstefano69 commented on influxdb.cpp
> +					Logger::getLogger()->fatal("Unable to connecto to influxDB server");
solved

2021-05-12 08:59 UTC, sstefano69 commented on influxdb.cpp
> +		Logger::getLogger()->error("xxx %s - Error while sending data %s", __FUNCTION__ , e.what());
solved

2021-05-12 09:01 UTC, MarkRiddoch approved these changes

2021-05-12 09:02 UTC, merged